name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-java:
    runs-on: ubuntu-latest  # Changed from matrix - Docker needs Linux
    
    steps:
    - uses: actions/checkout@v4  # Updated version
    
    - name: Set up JDK
      uses: actions/setup-java@v3  # Updated version
      with:
        java-version: '8'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: manisankarrr/demo-app  # Your Docker Hub repo name
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
        context: .  # Important for file paths
        dockerfile: Dockerfile
